name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Spring Boot Application
      run: mvn clean package

    - name: List files in the target directory
      run: ls -R target

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker buildx build -t ortheon/my-spring-app-blazej:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ortheon/my-spring-app-blazej:latest